# Generated by Django 4.2.4 on 2023-08-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='auther',
            field=models.CharField(blank=True, default='mohamed nasser', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='borrower_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
